language: rust
matrix:
  include:
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly
      env: EXP_FLAGS="--no-default-features"
script:
  - cargo test
  - if [ -n "$EXP_FLAGS" ]; then
      cargo test $EXP_FLAGS;
    fi
